schema = 3

[mod]
  [mod."github.com/stripe/stripe-go/v79"]
    version = "v79.12.0"
    hash = "sha256-ulOXI7G6nl4Pw7R2AsvOQPpWP+nArH+eIA8rhOQ9dSM="
  [mod."golang.org/x/net"]
    version = "v0.23.0"
    hash = "sha256-ZB4504rtgsHbcRfijjlqt4/2ddb8tyQB5IBn126uVTQ="
  [mod."gopkg.in/yaml.v3"]
    version = "v3.0.0"
    hash = "sha256-XWfvIV7+KXlZV4sBZd0srGeuQonS9cTYptCc6NcgVvc="
